### ISSUE TITLE
Use Percy for snapshot diffing

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/react-components#14]
We use Percy in Vanilla for snapshot diffing which is super helpful for catching visual regressions. It was also used in the old react components repo.
https://docs.percy.io/docs/storybook

@anthonydillon are you able to add @huwshimi and @squidsoup to the Percy account?

**Comment by anthonydillon** [comment]
@barrymcgee has the admin account on Percy. Could you please add @huwshimi  and @squidsoup

**Comment by barrymcgee** [comment]
Done.. 

(p.s. @anthonydillon - you, Peter, Karlos and Robin are also admins.)

**Comment by anthonydillon** [comment]
@barrymcgee thanks.

**Comment by squidsoup** [comment]
Percy is now configured and running in github actions. Unfortunately, due to the [fundamental limitation](https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/td-p/30678) making secrets unavailable for PRs from forks, PRs cannot be gated on percy. Percy does run against master on push however, and I've added a badge to the readme. Best we can do for now.
