### ISSUE TITLE
Add loading prop to Button

### ISSUE THREAD

**Issue by ClementChaumel** [canonical-web-and-design/react-components#468]
Would it be possible to add a `loading` / `isLoading` prop to the button component that would hide the text and show a spinner?

eg: 
```jsx
                  <Button
                    disabled={!valid}
                    appearance="positive"
                    className="col-small-2 col-medium-2 col-3 u-no-margin"
                    onClick={submitForm}
                    isLoading={isSubmitting}
                  >
                    Continue
                  </Button>
```

**Comment by hatched** [comment]
I'm not sure we want to tie the loading indicator to hiding of the text because in the Juju Dashboard we [show a "saving" message](https://github.com/canonical-web-and-design/jaas-dashboard/blob/master/src/panels/ConfigPanel/ConfigPanel.tsx#L316) while the spinner is active in the button.

To accomplish what you want right now I'd probably suggest using a ternary and changing the content of the button. Or you could use the vanilla class for [processing](https://vanillaframework.io/docs/patterns/buttons#processing) and pass it in via the `className` prop.

In the interest of supporting the vanilla feature set however adding a prop for [processing](https://vanillaframework.io/docs/patterns/buttons#processing) might be a good idea.

**Comment by huwshimi** [comment]
@ClementChaumel there is another component [ActionButton](https://canonical-web-and-design.github.io/react-components/?path=/docs/actionbutton--default-story) that might be what you want.

**Comment by ClementChaumel** [comment]
> @ClementChaumel there is another component [ActionButton](https://canonical-web-and-design.github.io/react-components/?path=/docs/actionbutton--default-story) that might be what you want.

I totally missed it for some reason that's exactly what I needed! Thanks!
